### ISSUE TITLE
No animations in Gnome

### ISSUE THREAD

**Issue by srt54558** [sabamdarif/gnome-in-termux#1]
Hello!
First off... Thanks! I absolutely love the setup script! It was so smooth and easy to set up!

But for some reason...
-now single animation works in gnome 
-i can't log in as a second user (im always logged in as root)

**Comment by sabamdarif** [comment]
> Hello! First off... Thanks! I absolutely love the setup script! It was so smooth and easy to set up!
> 
> But for some reason... -now single animation works in gnome -i can't log in as a second user (im always logged in as root)

which distro ? 
what do you mean by animation explain it 
and the error it showing while you login as second user send a screenshot it will be best

**Comment by srt54558** [comment]
> > Hello! First off... Thanks! I absolutely love the setup script! It was so smooth and easy to set up!
> > 
> > But for some reason... -now single animation works in gnome -i can't log in as a second user (im always logged in as root)
> 
> which distro ? 
> what do you mean by animation explain it 
> and the error it showing while you login as second user send a screenshot it will be best

I use proot Debian.

When I e.g. open the "All apps" menu, it just pops instead of transitioning from desktop to the collection of all apps. This is one, and the biggest example.

![Screenshot_20240218-195716.png](https://github.com/sabamdarif/gnome-in-termux/assets/90862487/7f95987d-55b6-4d80-9761-77b6bf2a86cf)

I can't find the exact log somehow but it's just all blank. But I can live with it and deleted the user

**Comment by sabamdarif** [comment]
> > > Hello! First off... Thanks! I absolutely love the setup script! It was so smooth and easy to set up!
> > > But for some reason... -now single animation works in gnome -i can't log in as a second user (im always logged in as root)
> > 
> > 
> > which distro ?
> > what do you mean by animation explain it
> > and the error it showing while you login as second user send a screenshot it will be best
> 
> I use proot Debian.
> 
> When I e.g. open the "All apps" menu, it just pops instead of transitioning from desktop to the collection of all apps. This is one, and the biggest example.
> 
> ![Screenshot_20240218-195716.png](https://private-user-images.githubusercontent.com/90862487/306734594-7f95987d-55b6-4d80-9761-77b6bf2a86cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzIwOTIsIm5iZiI6MTcxMDY3MTc5MiwicGF0aCI6Ii85MDg2MjQ4Ny8zMDY3MzQ1OTQtN2Y5NTk4N2QtNTViNi00ZDgwLTk3NjEtNzdiNmJmMmE4NmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEwMzYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNTQ1ZGJhM2IwOThkMTA4OTkxYWE4NGYyZTVmZGRlYWNiMTA2MTQwOGM3OGNjN2VkYWFiODcwMGViOWNiY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nTsCoh-Md3Fv6YLBb5labfIiZl06915tTAzBYsifai4)
> 
> I can't find the exact log somehow but it's just all blank. But I can live with it and deleted the user



> > > Hello! First off... Thanks! I absolutely love the setup script! It was so smooth and easy to set up!
> > > But for some reason... -now single animation works in gnome -i can't log in as a second user (im always logged in as root)
> > 
> > 
> > which distro ?
> > what do you mean by animation explain it
> > and the error it showing while you login as second user send a screenshot it will be best
> 
> I use proot Debian.
> 
> When I e.g. open the "All apps" menu, it just pops instead of transitioning from desktop to the collection of all apps. This is one, and the biggest example.
> 
> ![Screenshot_20240218-195716.png](https://private-user-images.githubusercontent.com/90862487/306734594-7f95987d-55b6-4d80-9761-77b6bf2a86cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzIwOTIsIm5iZiI6MTcxMDY3MTc5MiwicGF0aCI6Ii85MDg2MjQ4Ny8zMDY3MzQ1OTQtN2Y5NTk4N2QtNTViNi00ZDgwLTk3NjEtNzdiNmJmMmE4NmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEwMzYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNTQ1ZGJhM2IwOThkMTA4OTkxYWE4NGYyZTVmZGRlYWNiMTA2MTQwOGM3OGNjN2VkYWFiODcwMGViOWNiY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nTsCoh-Md3Fv6YLBb5labfIiZl06915tTAzBYsifai4)
> 
> I can't find the exact log somehow but it's just all blank. But I can live with it and deleted the user


type sudo service dbus start 
first then type vncstart , 
it will be fixed in next update

**Comment by sabamdarif** [comment]
> > > Hello! First off... Thanks! I absolutely love the setup script! It was so smooth and easy to set up!
> > > But for some reason... -now single animation works in gnome -i can't log in as a second user (im always logged in as root)
> > 
> > 
> > which distro ?
> > what do you mean by animation explain it
> > and the error it showing while you login as second user send a screenshot it will be best
> 
> I use proot Debian.
> 
> When I e.g. open the "All apps" menu, it just pops instead of transitioning from desktop to the collection of all apps. This is one, and the biggest example.
> 
> ![Screenshot_20240218-195716.png](https://private-user-images.githubusercontent.com/90862487/306734594-7f95987d-55b6-4d80-9761-77b6bf2a86cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzIwOTIsIm5iZiI6MTcxMDY3MTc5MiwicGF0aCI6Ii85MDg2MjQ4Ny8zMDY3MzQ1OTQtN2Y5NTk4N2QtNTViNi00ZDgwLTk3NjEtNzdiNmJmMmE4NmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEwMzYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiNTQ1ZGJhM2IwOThkMTA4OTkxYWE4NGYyZTVmZGRlYWNiMTA2MTQwOGM3OGNjN2VkYWFiODcwMGViOWNiY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nTsCoh-Md3Fv6YLBb5labfIiZl06915tTAzBYsifai4)
> 
> I can't find the exact log somehow but it's just all blank. But I can live with it and deleted the user

type sudo service dbus start 
first then type vncstart , 
it will be fixed in next update
