### ISSUE TITLE
Restore a previous version

### ISSUE THREAD

**Issue by IBRHIM190** [sabamdarif/gnome-in-termux#10]
We want to restore the previous version because of applying GNOME manually. I use a tool after installing Kali Linux and install it and it becomes original GNOME because of vncserver. I want to restore immediately!!!

**Comment by IBRHIM190** [comment]
I mean by programming

**Comment by sabamdarif** [comment]
do you mean you need to setup vnc ?

**Comment by sabamdarif** [comment]
add vnc setup steps https://github.com/sabamdarif/gnome-in-termux/commit/484bafd7b8e2084d6ad74ae0fbb44fff2a2d76ef

https://github.com/sabamdarif/gnome-in-termux?tab=readme-ov-file#how-to-setup-vnc

**Comment by IBRHIM190** [comment]
I do not mean going back to a previous version in a tool because I cannot install a tool in Kali Net Hunter

**Comment by sabamdarif** [comment]
> I do not mean going back to a previous version in a tool because I cannot install a tool in Kali Net Hunter

so what do you want ?

**Comment by IBRHIM190** [comment]
> > لا أقصد الرجوع إلى إصدار سابق في الأداة لأنني لا أستطيع تثبيت أداة في Kali Net Hunter
> 
> اذا ماذا تريد ؟

I just want to go back to a previous version

**Comment by sabamdarif** [comment]
> There is no easy way to rollback kali version 
but you can do one thing ,altough i don't know if it will 100%

but do can try it 
first setup tne kali cli with my modded-kali script , then download the older releases of kali nethunter nano, get hash value  value using `sha256sum  file-name`, remove kali `pd remove kali` move the kali-nano image to /data/data/com.termux/files/usr/var/lib/proot-distro/dlcache, edit $PREFIX/etc/proot-distro/kali.sh and add the new hash value then do `pd install kali`

**Comment by IBRHIM190** [comment]
> > There is no easy way to rollback kali version
> > but you can do one thing ,altough i don't know if it will 100%
> 
> but do can try it first setup tne kali cli with my modded-kali script , then download the older releases of kali nethunter nano, get hash value value using `sha256sum file-name`, remove kali `pd remove kali` move the kali-nano image to /data/data/com.termux/files/usr/var/lib/proot-distro/dlcache, edit $PREFIX/etc/proot-distro/kali.sh and add the new hash value then do `pd install kali`

Huh?

**Comment by IBRHIM190** [comment]
> > لا توجد طريقة سهلة لاستعادة إصدار كالي 
> > ولكن يمكنك القيام بشيء واحد، على الرغم من أنني لا أعرف ما إذا كان سيعمل بنسبة 100٪
> 
> لكن يمكنك تجربته أولاً لإعداد سطر أوامر kali باستخدام البرنامج النصي modded-kali الخاص بي، ثم تنزيل الإصدارات الأقدم من kali nethunter nano، والحصول على قيمة التجزئة باستخدام `sha256sum file-name`، وإزالة kali `pd remove kali`ونقل صورة kali-nano إلى /data/data/com.termux/files/usr/var/lib/proot-distro/dlcache، وتحرير $PREFIX/etc/proot-distro/kali.sh وإضافة قيمة التجزئة الجديدة ثم القيام بذلك`pd install kali`

I do not want to roll back the version of Kali Linux. I want to roll back the version of a tool because an update stopped downloading GNOME in my system

**Comment by sabamdarif** [comment]
> > > لا توجد طريقة سهلة لاستعادة إصدار كالي
> > > ولكن يمكنك القيام بشيء واحد، على الرغم من أنني لا أعرف ما إذا كان سيعمل بنسبة 100٪
> > 
> > 
> > لكن يمكنك تجربته أولاً لإعداد سطر أوامر kali باستخدام البرنامج النصي modded-kali الخاص بي، ثم تنزيل الإصدارات الأقدم من kali nethunter nano، والحصول على قيمة التجزئة باستخدام `sha256sum file-name`، وإزالة kali `pd remove kali`ونقل صورة kali-nano إلى /data/data/com.termux/files/usr/var/lib/proot-distro/dlcache، وتحرير $PREFIX/etc/proot-distro/kali.sh وإضافة قيمة التجزئة الجديدة ثم القيام بذلك`pd install kali`
> 
> I do not want to roll back the version of Kali Linux. I want to roll back the version of a tool because an update stopped downloading GNOME in my system

Download the old deb version then do sudo dpkg -i filename

**Comment by IBRHIM190** [comment]
> > > > لا توجد طريقة سهلة لطبعة كالي 
> > > > ولكن يمكنك القيام بواحدة، على الرغم من أدناه لا أعرف ما إذا كان سيعمل بنسبة 100٪
> > > 
> > > 
> > > لكن يمكنك الانتهاء من إعداد سطر أحكام kali باستخدام البرنامج النصي modded-kali الخاص بي، ثم تنزيل الاختلافات الأقدم من kali nethunter nano، النضج على القيمة المضافة باستخدام `sha256sum file-name`، تجديد kali ثم `pd remove kali`صورة kali-nano إلى /data/data/com.termux/files /usr/var/lib/proot-distro/dlcache، وتحرير $PREFIX/etc/proot-distro/kali.sh تفعيل القيمة الجديدة ثم القيام بذلك`pd install kali`
> > 
> > 
> > لا أريد التراجع عن إصدار Kali Linux. أريد التراجع عن إصدار أداة ما لأن أحد التحديثات أوقف تنزيل GNOME في نظامي
> 
> قم بتنزيل إصدار deb القديم ثم قم بتنفيذ sudo dpkg -i filename

How do I do it, and is there a way to recover the echoes of your device?

**Comment by IBRHIM190** [comment]
> > > > لا توجد طريقة سهلة لطبعة كالي 
> > > > ولكن يمكنك القيام بواحدة، على الرغم من أدناه لا أعرف ما إذا كان سيعمل بنسبة 100٪
> > > 
> > > 
> > > لكن يمكنك الانتهاء من إعداد سطر أحكام kali باستخدام البرنامج النصي modded-kali الخاص بي، ثم تنزيل الاختلافات الأقدم من kali nethunter nano، النضج على القيمة المضافة باستخدام `sha256sum file-name`، تجديد kali ثم `pd remove kali`صورة kali-nano إلى /data/data/com.termux/files /usr/var/lib/proot-distro/dlcache، وتحرير $PREFIX/etc/proot-distro/kali.sh تفعيل القيمة الجديدة ثم القيام بذلك`pd install kali`
> > 
> > 
> > لا أريد التراجع عن إصدار Kali Linux. أريد التراجع عن إصدار أداة ما لأن أحد التحديثات أوقف تنزيل GNOME في نظامي
> 
> قم بتنزيل إصدار deb القديم ثم قم بتنفيذ sudo dpkg -i filename

How do I retrieve the version of a tool?

**Comment by sabamdarif** [comment]
By tool what do you mean a package or a script or something else

**Comment by IBRHIM190** [comment]
> بأداة ماذا تقصد بالحزمة أو البرنامج النصي أو أي شيء آخر

everything

**Comment by IBRHIM190** [comment]
Recovering the version of a tool or deleting this thing in a picture
![Uploading VideoCapture_٢٠٢٤٠٧٢٦-٢٠٥٢٥٦.jpg…]()

**Comment by sabamdarif** [comment]
> > بأداة ماذا تقصد بالحزمة أو البرنامج النصي أو أي شيء آخر
> 
> everything
Checkout this :- https://unix.stackexchange.com/questions/79050/can-i-rollback-an-apt-get-upgrade-if-something-goes-wrong

**Comment by IBRHIM190** [comment]
> > > أداة ماذا تهدف إلى إضافة النصي أو أي شيء آخر
> > 
> > 
> > كل شيء 
> > تحقق من هذا: - https://unix.stackexchange.com/questions/79050/can-i-rollback-an-apt-get-upgrade-if-something-goes-wrong

?

**Comment by sabamdarif** [comment]
> > > > أداة ماذا تهدف إلى إضافة النصي أو أي شيء آخر
> > > 
> > > 
> > > كل شيء
> > > تحقق من هذا: - https://unix.stackexchange.com/questions/79050/can-i-rollback-an-apt-get-upgrade-if-something-goes-wrong
> 
> ?

check this post it will help you

**Comment by IBRHIM190** [comment]
> > > > > أداة التركيز على إضافة النص أو أي شيء آخر
> > > > 
> > > > 
> > > > كل شيء 
> > > > تحقق من هذا: - https://unix.stackexchange.com/questions/79050/can-i-rollback-an-apt-get-upgrade-if-something-goes-wrong
> > 
> > 
> > ؟
> 
> تحقق من هذا المنشور، سوف يساعدك

bash: /data/data/com.termux/files/usr/bin/kali: Permission denied

**Comment by sabamdarif** [comment]
chmod +x /data/data/com.termux/files/usr/bin/kali

**Comment by IBRHIM190** [comment]
> chmod +x /data/data/com.termux/files/usr/bin/kali

I just want to restore the tool version or delete Configuring Storage..,

**Comment by sabamdarif** [comment]
> > chmod +x /data/data/com.termux/files/usr/bin/kali
> 
> I just want to restore the tool version or delete Configuring Storage..,

Search it on Google; I tried my best.

Also, it's not related to this repo

**Comment by IBRHIM190** [comment]
?

**Comment by IBRHIM190** [comment]
> > > chmod +x /data/data/com.termux/files/usr/bin/kali
> > 
> > 
> > أريد فقط استعادة إصدار الأداة أو حذف تكوين التخزين..,
> 
> ابحث عنه على جوجل، لقد حاولت قصارى جهدي.
> 
> كما أنه ليس مرتبطًا بهذا المستودع

It has been solved and the GNOME desktop worked with my efforts. It has been solved
