### ISSUE TITLE
[proposal] Add the ability to change repository sources

### ISSUE THREAD

**Issue by hsragi** [sabamdarif/gnome-in-termux#11]
In some places, the download speed is particularly slow when installing, and it is recommended to provide an option for the user to change the repository sources before installing the software

**Comment by sabamdarif** [comment]
where you get this issue ?

**Comment by hsragi** [comment]
China，the default source for many Linux distributions is particularly slow to download in China.
There's a repository in China: 
https://mirrors.tuna.tsinghua.edu.cn/

**Comment by sabamdarif** [comment]
why don't you use vpn

**Comment by hsragi** [comment]
because it is ILLEGAL to use a VPN in China，and if i use vpn the installing process will be failed.

**Comment by sabamdarif** [comment]
i will try to add it in future , for now you can do one thing 

run the setup.sh then chose your linux distro then (e.g:- debian/arch) then when it says updating debian click CTRL + c and cancel the installation , then login into your linux distro ( `pd sh debian` ) , then open my repo 
download the installer script using wget 
For debian/ubuntu/kali :- `wget -O $HOME/gnome-installer.sh https://github.com/sabamdarif/gnome-in-termux/blob/main/install-gnome-desktop`

 For other:- `wget -O $HOME/gnome-installer.sh https://raw.githubusercontent.com/sabamdarif/gnome-in-termux/main/install-THE_DISTRO_NAME-gnome-desktop`
 
 **Change the mirror which work best for you**
 
` bash $HOME/gnome-installer.sh`
