### ISSUE TITLE
gnome-shell:14747): GLib-GIO-ERROR **: 02:46:53.326: Settings schema 'org.gnome.shell' is not installed Trace/breakpoint trap

### ISSUE THREAD

**Issue by IBRHIM190** [sabamdarif/gnome-in-termux#12]
I just want a solution

**Comment by sabamdarif** [comment]
i also get this error but gnome launch perfectly,
what problem you get ?

**Comment by IBRHIM190** [comment]
> أنا أيضًا أحصل على هذا الخطأ ولكن تشغيل Gnome مثالي، ما هي المشكلة التي تواجهها؟

I want to run a screen that does not work for me and it tells me this is an error

**Comment by IBRHIM190** [comment]
The problem was solved and I did it in VNC and this error appeared 
=================== tail /home/kali/.vnc/kali:1.log ===================

**Comment by IBRHIM190** [comment]
> i also get this error but gnome launch perfectly, what problem you get ?

The problem was solved and I did it in VNC and this error appeared
=================== tail /home/kali/.vnc/kali:1.log ===================

**Comment by sabamdarif** [comment]
use termux x11

**Comment by sabamdarif** [comment]
i recently remove the  vnc setup from the script because it create too much problem, and yes i add the vnc setup precess in readme beacause anyone want to use vnc so they can use the guide , but if it don't work for you then use termux x11

**Comment by IBRHIM190** [comment]
> لقد قمت مؤخرًا بإزالة إعداد VNC من البرنامج النصي لأنه يتسبب في الكثير من المشكلات، ونعم، أضفت عملية إعداد VNC في ملف readme لأن أي شخص يريد استخدام VNC حتى يتمكن من استخدام الدليل، ولكن إذا لم ينجح الأمر معك، فاستخدم termux x11

![Screenshot_٢٠٢٤٠٨١٢_١٢٤٩٣٩_NetHunter KeX](https://github.com/user-attachments/assets/6c37db86-0852-4d45-aa9b-0fff3ede1611)

**Comment by sabamdarif** [comment]
install a new icon pack then apply it

**Comment by IBRHIM190** [comment]
> قم بتثبيت حزمة أيقونات جديدة ثم قم بتطبيقها

![Screenshot_٢٠٢٤٠٨١٥_٠٧٢٣٥٧_NetHunter KeX](https://github.com/user-attachments/assets/5c9b0f96-cdf6-4420-a89c-a007defa9240)
Even a word  vncserver What is his famous word?

**Comment by IBRHIM190** [comment]
> قم بتثبيت حزمة أيقونات جديدة ثم قم بتطبيقها

The problem has been solved.
