### ISSUE TITLE
=================== tail /root/.vnc/kali:1.log ===================

### ISSUE THREAD

**Issue by IBRHIM190** [sabamdarif/gnome-in-termux#14]
I just want a solution and I don't want many details. I just want orders, I don't want anyone 
mistake  vnc

**Comment by sabamdarif** [comment]
Use termux x11

**Comment by sabamdarif** [comment]
thats why i remove vnc from the setup script , follow the guide from the readme if it work then it's good otherwise use termux x11 it best
