### ISSUE TITLE
Ubuntu full not opening when entering ubuntu

### ISSUE THREAD

**Issue by birdup000** [sabamdarif/gnome-in-termux#15]
Hi the script installed everything on a fresh install of Termux but there's an issue when I try to run the start commands ubuntu it won't start it says this 

![image](https://github.com/user-attachments/assets/e2673104-c756-46f3-af54-9edb3157c8b7)

**Comment by sabamdarif** [comment]
chmod +x /data/data/com.termux/files/usr/bin/ubuntu
