### ISSUE TITLE
no screen

### ISSUE THREAD

**Issue by Gamertoky11882gro** [sabamdarif/gnome-in-termux#2]
### **_i am only seeing a black screen how can i fix it_**
![Screenshot_20240531-184104](https://github.com/sabamdarif/gnome-in-termux/assets/142233819/6402c5b5-62d5-4766-a8b0-09f86ff2eeb7)
[](![Screenshot_20240531-184027](https://github.com/sabamdarif/gnome-in-termux/assets/142233819/e11f7d86-a584-4cec-9c1c-779a1f5937f4))

**Comment by sabamdarif** [comment]
go to $PREFIX/bin 
type nano ubuntu and send me what inside it

**Comment by sabamdarif** [comment]
also try running _for file in $(find /usr -type f -iname "*login1*"); do rm -rf $file
   done_ inside ubuntu not in termux

**Comment by sabamdarif** [comment]
which type of gnome desktop do you install core or full ?

**Comment by sabamdarif** [comment]
is it work with vnc ?

**Comment by Gamertoky11882gro** [comment]
full

**Comment by Gamertoky11882gro** [comment]
no https://drive.google.com/file/d/1JSrEw1oOHkZ4tAsKfmUQSb9latoAU4Xp/view?usp=sharing

**Comment by sabamdarif** [comment]
Install the latest version of [Termux:x11](https://github.com/termux/termux-x11/releases/tag/nightly)

Then

termux_x11_pid=$(pgrep -f /system/bin/app_process.*com.termux.x11.Loader)
xfce_pid=$(pgrep -f "xfce4-session")
if [ -n "$termux_x11_pid" ] || [ -n "$xfce_pid" ]; then
  kill -9 "$termux_x11_pid" "$xfce_pid" > /dev/null 2>&1
echo "Termux:X11 Stopped Successfully"
fi

save this on a bash file (like: stop.sh) and run it then try again launching termux x11 (using: ubuntu -tx11)

**Comment by Gamertoky11882gro** [comment]
my device isn't support termux-x11 latest version so i use
app-armeabi-v7a-debug.apk
<https://github.com/termux/termux-x11/releases/download/nightly/app-armeabi-v7a-debug.apk>

**Comment by sabamdarif** [comment]
and did you run the script ?

**Comment by Gamertoky11882gro** [comment]
Yes, I did.

**Comment by sabamdarif** [comment]
can you send me a screen recording of what happening when you launch termux x11 , a full video of it

**Comment by sabamdarif** [comment]
because i try both core and full and they work just fine

**Comment by Gamertoky11882gro** [comment]
can i send u a google drive screen record video link

**Comment by Gamertoky11882gro** [comment]
https://drive.google.com/file/d/1vi7fBxirxm9tUtlymgE1076yI5rmEEl1/view?usp=sharing

**Comment by sabamdarif** [comment]
try launching it as root

STEPS:-

go to $PREFIX/bin
nano ubuntu-root

pest this 
________________________________________________________________

rm ~/.cache/sessions/x*
termux_x11_pid=$(pgrep -f /system/bin/app_process.*com.termux.x11.Loader)
xfce_pid=$(pgrep -f "xfce4-session")
if [ -n "$termux_x11_pid" ] || [ -n "$xfce_pid" ]; then
  kill -9 "$termux_x11_pid" "$xfce_pid" > /dev/null 2>&1
echo "termux:x11 kill successfully"
fi
if [ "$1" = "-tx11" ]; then
    kill -9 $(pgrep -f "termux.x11") 2>/dev/null
termux-x11 :0 >/dev/null &
sleep 3
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1
sleep 1
proot-distro login ubuntu --shared-tmp -- /bin/bash -c "service dbus start && export XDG_CURRENT_DESKTOP="GNOME" && env DISPLAY=:0 gnome-shell --x11"
exit 0
fi
_____________________________________________________________________________
CTRL  + s , CTRL + x
chmod +x ubuntu-root

ubuntu-root -tx11

**Comment by Gamertoky11882gro** [comment]
not working.

                but i have an idea. you can send me termux backup. then i
restore backup file in my termux. you can create backup with this commands
cd $PREFIX/../../ && tar -cvf /storage/emulated/0/backup.tar ./files

**Comment by Gamertoky11882gro** [comment]
give me ubuntu core backup

**Comment by sabamdarif** [comment]
ok

**Comment by Gamertoky11882gro** [comment]
now send me backup

**Comment by Gamertoky11882gro** [comment]
please try to give fast

**Comment by sabamdarif** [comment]
https://mega.nz/file/MJphyaJI#Z-PPDkivKVXF0P9_L03Z_ih3ZE1EP28hQGtkKPOUGdI

**Comment by Gamertoky11882gro** [comment]
please give me drive download link. i face some problem to download to mega

**Comment by sabamdarif** [comment]
are you in telegram ?

**Comment by Gamertoky11882gro** [comment]
Yes I have telegram

**Comment by sabamdarif** [comment]
DM me there 
t.me/saba_mdarif
