### ISSUE TITLE
not a work vnc and termux x11

### ISSUE THREAD

**Issue by binrusdi** [sabamdarif/gnome-in-termux#4]
command : ubuntu -tx11
result : 
![Screenshot_20240618-094307](https://github.com/sabamdarif/gnome-in-termux/assets/119654495/ee966d52-3e94-4280-917e-2668b5c86a57)
![Screenshot_20240618-094318](https://github.com/sabamdarif/gnome-in-termux/assets/119654495/44e04174-2536-4cac-a522-c66123943491)

command : ubuntu -vncstart
result : 
![Screenshot_20240618-094734](https://github.com/sabamdarif/gnome-in-termux/assets/119654495/bb2a54fd-80e4-4cbd-9bc6-3e4617fbf150)

**Comment by binrusdi** [comment]
can you help me

**Comment by sabamdarif** [comment]
login into ubuntu and run `sudo rm -rf /tmp/.X*` then run `pkill Xtigervnc ` , `rm $HOME/.vnc/localhost:*.log` , `rm /tmp/.X11-unix/X1` after that type vncstart in ubuntu

**Comment by binrusdi** [comment]
if a use termux 11, how to?

**Comment by sabamdarif** [comment]
> if a use termux 11, how to?

do that first then remove then ununtu do `rm -rf $HOME/.cache` and in termux do `pkill -f com.termux.x11` force stop termux
and then again launching termux x11 

I think it will work

**Comment by binrusdi** [comment]
for vnc it's work, and when running -tx11 display a cursor only on blackscreen.
for setting tx11, where location file?
maybe i must add `-legacy-drawing`

**Comment by sabamdarif** [comment]
`cd $PREFIX/bin`
`nano ubuntu`

tell me if you manage to fix it

**Comment by binrusdi** [comment]
Sorry, for termux-x11. maybe mush giveup.
because message error "-legacy-drawing not command".
but to vnc, it is can goes well.

tengkyu very much..
I will close this issue with resolved

**Comment by sabamdarif** [comment]
> Sorry, for termux-x11. maybe mush giveup. because message error "-legacy-drawing not command". but to vnc, it is can goes well.
> 
> tengkyu very much.. I will close this issue with resolved

if you can , you can give me the backup of the ubuntu so i can check it my self .

 can you send me what inside the ubuntu file in $PREFIX/bin folder

**Comment by binrusdi** [comment]
oke, wait
can me send my file

**Comment by binrusdi** [comment]
oh sorry, i have remove the file
because have choose termux-desktop your repo.

**Comment by sabamdarif** [comment]
ok , then I will try to figure it out

**Comment by sabamdarif** [comment]
what is your device architecture and android version ?

**Comment by sabamdarif** [comment]
> aarch64, android 9

go to `$PREFIX/bin`
type `nano ubuntu`
replace the `termux-x11 :0 >/dev/null &`
with 
`termux-x11 :0 -legacy-drawing >/dev/null &`
