### ISSUE TITLE
Hardware acceleration 

### ISSUE THREAD

**Issue by srt54558** [sabamdarif/gnome-in-termux#5]
Hello,
As gnome uses software rendering, there are no animations in gnome and programs are slower. I managed to install turnip Vulkan drivers for  my adreno 740, so most apps got hw acceleration now. But I don't get how to make gnome have/use these drivers or enable HW acceleration for the animations to unlock.

Do you perhaps know a bit more on how to fix this?

**Comment by sabamdarif** [comment]
here to access the gui i use the x11 server and x11 have no animation by default only wayland have animation , but for wayland restriction we can't share display ,  I think there might be some way to get animation in x11 but i sure it don't gonna work in termux .
And for using the  hardware acceleration  launch app with this command :- `MESA_LOADER_DRIVER_OVERRIDE=zink TU_DEBUG=noconform programe_name`
