### ISSUE TITLE
How to connect vnc

### ISSUE THREAD

**Issue by HACKER28012006** [sabamdarif/gnome-in-termux#6]
New Xtigervnc server 'localhost.localdomain:1 (sampathvarma)' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /tmp/tigervnc.D7Cdfc/passwd :1 to connect to the VNC server.

It is showing like this , 
What I need to enter in vncviewer

**Comment by sabamdarif** [comment]
first login into that distro like for ubuntu type `ubuntu` in termux
then type `vncstop -f` if it don't work then only `vncstop`
then type `vncstart`

**Comment by sabamdarif** [comment]
Vnc has been removed because it creates too much problems https://github.com/sabamdarif/gnome-in-termux/commit/3136915c878bf818ea3966cb39d230d28f98c87e
