### ISSUE TITLE
Vnc

### ISSUE THREAD

**Issue by HACKER28012006** [sabamdarif/gnome-in-termux#7]
Removing stale PID file /var/run/dbus/pid.
 * Starting system message bus dbus             [ OK ]

New Xtigervnc server 'localhost.localdomain:1 (sampathvarma)' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /tmp/tigervnc.hXJUku/passwd :1 to connect to the VNC server.

=================== tail /home/sampathvarma/.vnc/localhost.localdomain:1.log ===================
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
[mi] mieq: warning: overriding existing handler (nil) with 0x30001e0ec0 for event 2
[mi] mieq: warning: overriding existing handler (nil) with 0x30001e0ec0 for event 3
libmutter-Message: 11:19:31.524: Running GNOME Shell (using mutter 46.0) as a X11 window and compositing manager
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
Xlib:  extension "DPMS" missing on display ":1".
Window manager warning: Impossible to set scaling on crtc 58 to 1.000000, error id 2
Window manager warning: Scalig CRTC 58 at 1.000000 failed

Xlib:  extension "DPMS" missing on display ":1".
Failed to connect to session bus: Failed to close file descriptor for child process (Invalid argument)
================================================================================================

Session startup via '/home/sampathvarma/.vnc/xstartup' exited with status 1!

Maybe try something simple first, e.g.,
        tigervncserver -xstartup /usr/bin/xterm
The X session exited with status 1!
Killing Xtigervnc process ID 12722... success!

**Comment by sabamdarif** [comment]
type `nano /home/sampathvarma/.vnc/xstartup` and send me what inside it

**Comment by HACKER28012006** [comment]
export XDG_CURRENT_DESKTOP="GNOME"
gnome-shell --x11

**Comment by sabamdarif** [comment]
which distro ?

**Comment by sabamdarif** [comment]
try killing the vncserver and relaunch it , type the vncstart command inside the distro not from termux

**Comment by HACKER28012006** [comment]
HOW CAN I INSTALL GAMES IN TERMUX DESKTOP

**Comment by sabamdarif** [comment]
Which games , windows games ?

**Comment by HACKER28012006** [comment]
ANY PLAYABLE GAMES IN TERMUX DESKTOP

**Comment by sabamdarif** [comment]
Use this it will help you to install windows game in termux https://github.com/ahmad1abbadi/darkos

**Comment by HACKER28012006** [comment]
In your gnome is it possible, instead of installing another dark os

**Comment by HACKER28012006** [comment]
In kali modded can I install?

**Comment by sabamdarif** [comment]
you can't install darkos in kali but if you really want to install games in kali use box64 + wine , altough i don't recomend it .
If yoy really want to play games use darkos separately

**Comment by sabamdarif** [comment]
soon i will add support for darkos in termux desktop , so anyone use it alonside with it

**Comment by sabamdarif** [comment]
As for the your main issue i update the installer check if your problem fixed or not

**Comment by sabamdarif** [comment]
Vnc has been removed because it creates too much problems https://github.com/sabamdarif/gnome-in-termux/commit/3136915c878bf818ea3966cb39d230d28f98c87e

**Comment by IBRHIM190** [comment]
everything
