### ISSUE TITLE
add distros

### ISSUE THREAD

**Issue by Fulanito0** [sabamdarif/gnome-in-termux#8]
Hello sabamdarif.
Termux added alpine a few days ago to their proot-distro list, if you could create a script to automate the installation so that people can install docker on top of it, I think it would be very beneficial for the community that have discovered your github.

Why didn't you leave the vncserver installation as an option to choose in a list for users to choose if I want a native graphical interface or with a third party app ?

Since I am here and I did not find a social network through which I could communicate with you and ask you, I was forced to ask you here about the media and rolling distros that appear in an option list next to the full version of ubuntu and kali, I want to know how you get the other lighter versions of rooft, if they are in a hidden part of the official pages or are modifications of full versions to weigh less and the users who install them can customize them ?

I want to get clean versions of rooft x86 to customize and secure them. I saw that you install nethunter in the kali script, hopefully you can provide the desktop version.

**Comment by sabamdarif** [comment]
t.me/saba_mdarif

Came here

**Comment by Fulanito0** [comment]
Thank you for such a good job you do.
